// src/routes/[[lang=lang]]/dashboard/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths'
	import { useQuery } from 'convex-svelte'
	import { useClerkContext, SignOutButton } from 'svelte-clerk'
	import { api } from '$convex/api'

	type Tab = 'booking' | 'profile' | 'docs'

	const ctx = useClerkContext()
	const firstName = $derived(ctx.user?.firstName ?? 'Żeglarz')
	const userId = $derived(ctx.auth.userId ?? '')

	let tab = $state<Tab>('booking')

	// ── Convex queries ────────────────────────────────────────────────────
	const bookingQuery = useQuery(api.queries.bookingByUser, () => ({ userId }))
	const profileQuery = useQuery(api.queries.crewProfileByUser, () => ({
		userId
	}))

	const bookingData = $derived(bookingQuery.data)
	const profileData = $derived(profileQuery.data)

	// ── Derived display data from Convex (falls back to placeholders) ─────
	const bookingRows = $derived<ReadonlyArray<readonly [string, string]>>(
		bookingData
			? [
					['Ref', bookingData.bookingRef],
					['Etap', bookingData.segment?.name ?? '—'],
					['Termin', bookingData.segment?.dates ?? '—'],
					['Dni', String(bookingData.segment?.days ?? '—')],
					[
						'Status',
						bookingData.status === 'confirmed'
							? 'Potwierdzona'
							: 'Oczekuje na płatność'
					],
					[
						'Cena',
						`${(bookingData.segment?.pricePerBerth ?? 0).toLocaleString('pl-PL')} zł`
					]
				]
			: []
	)

	const profile = $derived<ReadonlyArray<readonly [string, string]>>(
		profileData
			? [
					[
						'Imię i nazwisko',
						`${profileData.firstName} ${profileData.lastName}`
					],
					['Data urodzenia', profileData.dateOfBirth],
					['Narodowość', profileData.nationality],
					[
						'Typ dokumentu',
						profileData.docType === 'passport' ? 'Paszport' : 'Dowód osobisty'
					],
					['Numer dokumentu', profileData.docNumber],
					['Kontakt alarmowy', profileData.emergencyContactName],
					['Tel. alarmowy', profileData.emergencyContactPhone],
					['Umiejętności pływackie', profileData.swimmingAbility],
					['Doświadczenie', profileData.sailingExperience]
				]
			: []
	)

	// Timeline ports — static for Sail Adventure 2026
	const ports = [
		{ port: 'Palma de Mallorca', date: '4.10', active: false },
		{ port: 'Gibraltar', date: '11.10', active: true },
		{ port: 'Madera', date: '21.10', active: true },
		{ port: 'Teneryfa', date: '31.10', active: false },
		{ port: 'Cabo Verde', date: '14.11', active: false }
	]

	function legActive(i: number): boolean {
		return ports[i]?.active === true && ports[i + 1]?.active === true
	}

	const docs = [
		{ name: 'Potwierdzenie rezerwacji', date: '24.04.2026', type: 'PDF' },
		{ name: 'Regulamin rejsu', date: '01.01.2026', type: 'PDF' },
		{ name: 'Lista rzeczy do zabrania', date: '01.01.2026', type: 'PDF' },
		{ name: 'Plan trasy szczegółowy', date: '01.03.2026', type: 'PDF' }
	]

	const tabs: ReadonlyArray<{ id: Tab; label: string }> = [
		{ id: 'booking', label: 'Rezerwacja' },
		{ id: 'profile', label: 'Dane załogi' },
		{ id: 'docs', label: 'Dokumenty' }
	]
</script>

<svelte:head>
	<title>Panel · Sailing Architects</title>
</svelte:head>

<main class="dash">
	<div class="dash__inner">
		<header class="dash__header">
			<div>
				<a class="dash__back" href={resolve('/')}>← Strona główna</a>
				<p class="eyebrow">Panel użytkownika</p>
				<h1 class="dash__title">Cześć, {firstName}</h1>
			</div>
			<div class="dash__header-right">
				{#if bookingData}
					<div class="dash__ref">
						<p class="dash__ref-label">Numer rezerwacji</p>
						<p class="dash__ref-value">{bookingData.bookingRef}</p>
					</div>
				{/if}
				<SignOutButton class="btn btn--signout">Wyloguj</SignOutButton>
			</div>
		</header>

		<div class="tabs" role="tablist" aria-label="Sekcje panelu">
			{#each tabs as t (t.id)}
				<button
					type="button"
					role="tab"
					aria-selected={tab === t.id}
					aria-controls={`panel-${t.id}`}
					class="tabs__btn"
					class:tabs__btn--active={tab === t.id}
					onclick={() => (tab = t.id)}
				>
					{t.label}
				</button>
			{/each}
		</div>

		{#if tab === 'booking'}
			<div id="panel-booking" role="tabpanel">
				<div class="status">
					<span class="status__dot" aria-hidden="true"></span>
					<span class="status__text"
						>Rezerwacja potwierdzona · Płatność zrealizowana</span
					>
				</div>

				<article class="voyage">
					<header class="voyage__header">
						<p class="voyage__eyebrow">Sail Adventure 2026</p>
						<h3 class="voyage__title">{bookingData?.segment?.name ?? '—'}</h3>
					</header>
					{#if bookingRows.length}
						<dl class="voyage__rows">
							{#each bookingRows as [label, value] (label)}
								<div class="voyage__cell">
									<dt class="voyage__label">{label}</dt>
									<dd class="voyage__value">{value}</dd>
								</div>
							{/each}
						</dl>
					{:else}
						<p class="voyage__empty">Brak aktywnej rezerwacji.</p>
					{/if}
				</article>

				<section class="timeline">
					<p class="timeline__title">Cała trasa rejsu</p>
					<ol class="timeline__list" aria-label="Porty na trasie">
						{#each ports as p, i (p.port)}
							<li
								class="timeline__port"
								class:timeline__port--active={p.active}
							>
								<span class="timeline__diamond" aria-hidden="true"></span>
								<span class="timeline__name">{p.port}</span>
								<span class="timeline__date">{p.date}</span>
							</li>
							{#if i < ports.length - 1}
								<span
									class="timeline__leg"
									class:timeline__leg--active={legActive(i)}
									aria-hidden="true"
								></span>
							{/if}
						{/each}
					</ol>
				</section>

				<div class="actions">
					<button type="button" class="btn btn--primary" disabled
						>↓ Pobierz potwierdzenie</button
					>
					<button type="button" class="btn btn--ghost" disabled
						>Kontakt z organizatorem</button
					>
				</div>
			</div>
		{/if}

		{#if tab === 'profile'}
			<div id="panel-profile" role="tabpanel">
				<p class="lead">
					Dane wymagane przez kapitana. Możesz je aktualizować do 30 dni przed
					rejsem.
				</p>
				{#if profile.length}
					<div class="profile">
						{#each profile as [label, value] (label)}
							<div class="profile__card">
								<p class="profile__label">{label}</p>
								<p class="profile__value">{value}</p>
							</div>
						{/each}
					</div>
					<button type="button" class="btn btn--outline" disabled
						>Edytuj dane</button
					>
				{:else}
					<p class="voyage__empty">Profil nie został jeszcze uzupełniony.</p>
				{/if}
			</div>
		{/if}

		{#if tab === 'docs'}
			<div id="panel-docs" role="tabpanel">
				<p class="lead">Dokumenty do pobrania</p>
				<ul class="docs">
					{#each docs as doc (doc.name)}
						<li>
							<button type="button" class="docs__item" disabled>
								<div class="docs__text">
									<p class="docs__name">{doc.name}</p>
									<p class="docs__meta">{doc.type} · {doc.date}</p>
								</div>
								<span class="docs__icon" aria-hidden="true">↓</span>
							</button>
						</li>
					{/each}
				</ul>
			</div>
		{/if}
	</div>
</main>

<style>
	.dash {
		min-height: 100vh;
		background: var(--color-navy);
		padding: 124px 24px 80px;
	}

	.dash__inner {
		max-width: 860px;
		margin: 0 auto;
	}

	.dash__header {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		margin-bottom: 48px;
		flex-wrap: wrap;
		gap: 16px;
	}

	.dash__header-right {
		display: flex;
		align-items: flex-start;
		gap: 16px;
		flex-wrap: wrap;
	}

	:global(.btn--signout) {
		font-family: var(--font-sans);
		text-transform: uppercase;
		letter-spacing: 2px;
		font-size: 11px;
		padding: 12px 24px;
		background: none;
		border: 1px solid rgba(196, 146, 58, 0.3);
		color: rgba(245, 240, 232, 0.6);
		cursor: pointer;
		border-radius: 0;
		transition:
			background-color 200ms ease,
			color 200ms ease,
			border-color 200ms ease;
	}

	:global(.btn--signout:hover) {
		color: var(--color-warm-white);
		border-color: var(--color-brass);
		background: rgba(196, 146, 58, 0.06);
	}

	.dash__back {
		background: none;
		border: none;
		color: rgba(196, 146, 58, 0.5);
		font-family: var(--font-sans);
		font-size: 11px;
		letter-spacing: 2px;
		text-transform: uppercase;
		cursor: pointer;
		padding: 0;
		margin-bottom: 20px;
		display: block;
		text-decoration: none;
		transition: color 200ms ease;
	}

	.dash__back:hover {
		color: var(--color-brass);
	}

	.eyebrow {
		font-family: var(--font-sans);
		font-size: 11px;
		letter-spacing: 3px;
		color: rgba(196, 146, 58, 0.6);
		text-transform: uppercase;
		margin: 0 0 6px;
	}

	.dash__title {
		font-family: var(--font-serif);
		font-size: 32px;
		font-weight: 400;
		color: var(--color-warm-white);
		margin: 0;
	}

	.dash__ref {
		padding: 12px 20px;
		border: 1px solid rgba(196, 146, 58, 0.25);
		background: rgba(196, 146, 58, 0.05);
	}

	.dash__ref-label {
		font-family: var(--font-sans);
		font-size: 9px;
		letter-spacing: 2px;
		text-transform: uppercase;
		color: rgba(196, 146, 58, 0.5);
		margin: 0 0 4px;
	}

	.dash__ref-value {
		font-family: var(--font-serif);
		font-size: 20px;
		color: var(--color-brass);
		margin: 0;
	}

	.tabs {
		border-bottom: 1px solid rgba(196, 146, 58, 0.15);
		margin-bottom: 40px;
		display: flex;
		flex-wrap: wrap;
	}

	.tabs__btn {
		padding: 10px 24px;
		background: none;
		border: none;
		border-bottom: 2px solid transparent;
		color: rgba(245, 240, 232, 0.4);
		font-family: var(--font-sans);
		font-size: 12px;
		letter-spacing: 1px;
		text-transform: uppercase;
		cursor: pointer;
		margin-bottom: -1px;
		transition:
			color 200ms ease,
			border-color 200ms ease;
	}

	.tabs__btn:hover {
		color: rgba(245, 240, 232, 0.7);
	}

	.tabs__btn--active {
		color: var(--color-brass);
		border-bottom-color: var(--color-brass);
	}

	.status {
		display: flex;
		align-items: center;
		gap: 12px;
		padding: 14px 20px;
		background: rgba(80, 160, 80, 0.08);
		border: 1px solid rgba(80, 160, 80, 0.25);
		margin-bottom: 32px;
	}

	.status__dot {
		width: 8px;
		height: 8px;
		background: #50a050;
		border-radius: 50%;
		flex-shrink: 0;
	}

	.status__text {
		font-family: var(--font-sans);
		font-size: 12px;
		color: rgba(245, 240, 232, 0.7);
		letter-spacing: 0.5px;
	}

	.voyage {
		border: 1px solid rgba(196, 146, 58, 0.2);
		margin-bottom: 32px;
	}

	.voyage__header {
		padding: 20px 24px;
		background: rgba(196, 146, 58, 0.06);
		border-bottom: 1px solid rgba(196, 146, 58, 0.12);
	}

	.voyage__eyebrow {
		font-family: var(--font-sans);
		font-size: 10px;
		letter-spacing: 2px;
		text-transform: uppercase;
		color: rgba(196, 146, 58, 0.6);
		margin: 0 0 4px;
	}

	.voyage__title {
		font-family: var(--font-serif);
		font-size: 22px;
		font-weight: 400;
		color: var(--color-warm-white);
		margin: 0;
	}

	.voyage__empty {
		font-family: var(--font-sans);
		font-size: 13px;
		color: rgba(245, 240, 232, 0.3);
		padding: 24px;
		margin: 0;
	}

	.voyage__rows {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
		margin: 0;
	}

	.voyage__cell {
		padding: 16px 20px;
		border-right: 1px solid rgba(196, 146, 58, 0.08);
		border-bottom: 1px solid rgba(196, 146, 58, 0.08);
	}

	.voyage__label {
		font-family: var(--font-sans);
		font-size: 9px;
		letter-spacing: 2px;
		text-transform: uppercase;
		color: rgba(196, 146, 58, 0.45);
		margin: 0 0 4px;
	}

	.voyage__value {
		font-family: var(--font-sans);
		font-size: 14px;
		font-weight: 500;
		color: var(--color-warm-white);
		margin: 0;
	}

	.timeline {
		margin-bottom: 32px;
	}

	.timeline__title {
		font-family: var(--font-sans);
		font-size: 10px;
		letter-spacing: 2px;
		text-transform: uppercase;
		color: rgba(196, 146, 58, 0.5);
		margin: 0 0 16px;
	}

	.timeline__list {
		list-style: none;
		padding: 0 0 8px;
		margin: 0;
		display: flex;
		align-items: center;
		gap: 0;
		overflow-x: auto;
	}

	.timeline__port {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 4px;
		min-width: 80px;
		flex-shrink: 0;
	}

	.timeline__diamond {
		width: 10px;
		height: 10px;
		border: 1.5px solid rgba(196, 146, 58, 0.3);
		background: transparent;
		transform: rotate(45deg);
		flex-shrink: 0;
	}

	.timeline__port--active .timeline__diamond {
		border-color: var(--color-brass);
		background: var(--color-brass);
	}

	.timeline__name {
		font-family: var(--font-sans);
		font-size: 10px;
		color: rgba(245, 240, 232, 0.35);
		text-align: center;
		line-height: 1.3;
	}

	.timeline__port--active .timeline__name {
		color: var(--color-warm-white);
	}

	.timeline__date {
		font-family: var(--font-sans);
		font-size: 9px;
		color: rgba(196, 146, 58, 0.3);
	}

	.timeline__port--active .timeline__date {
		color: var(--color-brass);
	}

	.timeline__leg {
		flex: 1;
		height: 1px;
		background: rgba(196, 146, 58, 0.15);
		min-width: 24px;
		margin-bottom: 30px;
	}

	.timeline__leg--active {
		background: var(--color-brass);
	}

	.actions {
		display: flex;
		gap: 12px;
		flex-wrap: wrap;
	}

	.btn {
		font-family: var(--font-sans);
		text-transform: uppercase;
		letter-spacing: 2px;
		font-size: 11px;
		cursor: pointer;
		border-radius: 0;
		text-decoration: none;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		transition:
			background-color 200ms ease,
			color 200ms ease,
			border-color 200ms ease;
	}

	.btn--primary {
		padding: 12px 28px;
		background: var(--color-brass);
		border: none;
		color: var(--color-navy);
		font-weight: 700;
	}

	.btn--primary:hover:not(:disabled) {
		background: var(--color-brass-light);
	}

	.btn--ghost {
		padding: 12px 24px;
		background: none;
		border: 1px solid rgba(196, 146, 58, 0.25);
		color: rgba(245, 240, 232, 0.5);
	}

	.btn--ghost:hover:not(:disabled) {
		color: var(--color-warm-white);
		border-color: var(--color-brass);
	}

	.btn--outline {
		padding: 12px 28px;
		background: none;
		border: 1px solid rgba(196, 146, 58, 0.35);
		color: var(--color-brass);
		margin-top: 28px;
	}

	.btn--outline:hover:not(:disabled) {
		background: rgba(196, 146, 58, 0.06);
	}

	.btn:disabled {
		opacity: 0.55;
		cursor: not-allowed;
	}

	.lead {
		font-family: var(--font-sans);
		font-size: 13px;
		line-height: 1.6;
		color: rgba(245, 240, 232, 0.4);
		margin: 0 0 32px;
	}

	.profile {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
		gap: 20px;
		max-width: 600px;
	}

	.profile__card {
		padding: 14px 16px;
		background: rgba(255, 255, 255, 0.03);
		border-left: 2px solid rgba(196, 146, 58, 0.2);
	}

	.profile__label {
		font-family: var(--font-sans);
		font-size: 9px;
		letter-spacing: 2px;
		text-transform: uppercase;
		color: rgba(196, 146, 58, 0.45);
		margin: 0 0 4px;
	}

	.profile__value {
		font-family: var(--font-sans);
		font-size: 13px;
		color: var(--color-warm-white);
		margin: 0;
	}

	.docs {
		list-style: none;
		padding: 0;
		margin: 0;
	}

	.docs li {
		margin-bottom: 8px;
	}

	.docs__item {
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 16px 20px;
		border: 1px solid rgba(196, 146, 58, 0.12);
		background: none;
		cursor: pointer;
		text-align: left;
		font-family: inherit;
		transition:
			border-color 200ms ease,
			background-color 200ms ease;
	}

	.docs__item:hover:not(:disabled) {
		border-color: var(--color-brass);
		background: rgba(196, 146, 58, 0.04);
	}

	.docs__item:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.docs__name {
		font-family: var(--font-sans);
		font-size: 13px;
		color: var(--color-warm-white);
		margin: 0 0 2px;
	}

	.docs__meta {
		font-family: var(--font-sans);
		font-size: 10px;
		color: rgba(245, 240, 232, 0.3);
		margin: 0;
	}

	.docs__icon {
		font-family: var(--font-sans);
		font-size: 11px;
		color: var(--color-brass);
		letter-spacing: 1px;
	}

	@media (max-width: 640px) {
		.dash {
			padding: 100px 16px 60px;
		}
	}
</style>

// docs/design/design_handoff_sailing_architects/components/dashboard.jsx
// Dashboard — user's booking summary + profile management

function Dashboard({ onBack }) {
	const [tab, setTab] = React.useState('booking')
	const booking = {
		seg: {
			name: 'Gibraltar → Madera',
			dates: '12–21.10.2026',
			days: 9,
			price: 2300
		},
		berth: 'B1',
		cabin: 'Kabina B',
		position: 'Rufowa lewa',
		status: 'confirmed',
		paid: true,
		ref: 'SA-2026-0047'
	}

	const TabBtn = ({ id, label }) => (
		<button
			onClick={() => setTab(id)}
			style={{
				padding: '10px 24px',
				background: 'none',
				border: 'none',
				borderBottom: `2px solid ${tab === id ? '#c4923a' : 'transparent'}`,
				color: tab === id ? '#c4923a' : 'rgba(245,240,232,0.4)',
				fontFamily: 'DM Sans, sans-serif',
				fontSize: '12px',
				letterSpacing: '1px',
				textTransform: 'uppercase',
				cursor: 'pointer',
				marginBottom: '-1px'
			}}
		>
			{label}
		</button>
	)

	return (
		<div
			style={{
				minHeight: '100vh',
				background: '#0d1b2e',
				padding: '60px 24px'
			}}
		>
			<div style={{ maxWidth: '860px', margin: '0 auto' }}>
				{/* Header */}
				<div
					style={{
						display: 'flex',
						justifyContent: 'space-between',
						alignItems: 'flex-start',
						marginBottom: '48px',
						flexWrap: 'wrap',
						gap: '16px'
					}}
				>
					<div>
						<button
							onClick={onBack}
							style={{
								background: 'none',
								border: 'none',
								color: 'rgba(196,146,58,0.5)',
								fontFamily: 'DM Sans, sans-serif',
								fontSize: '11px',
								letterSpacing: '2px',
								textTransform: 'uppercase',
								cursor: 'pointer',
								padding: 0,
								marginBottom: '20px',
								display: 'block'
							}}
						>
							← Strona główna
						</button>
						<p
							style={{
								fontFamily: 'DM Sans, sans-serif',
								fontSize: '11px',
								letterSpacing: '3px',
								color: 'rgba(196,146,58,0.6)',
								textTransform: 'uppercase',
								margin: '0 0 6px'
							}}
						>
							Panel użytkownika
						</p>
						<h1
							style={{
								fontFamily: 'Playfair Display, serif',
								fontSize: '32px',
								color: '#f5f0e8',
								margin: 0,
								fontWeight: '400'
							}}
						>
							Cześć, Michał
						</h1>
					</div>
					<div
						style={{
							padding: '12px 20px',
							border: '1px solid rgba(196,146,58,0.25)',
							background: 'rgba(196,146,58,0.05)'
						}}
					>
						<p
							style={{
								fontFamily: 'DM Sans, sans-serif',
								fontSize: '9px',
								letterSpacing: '2px',
								textTransform: 'uppercase',
								color: 'rgba(196,146,58,0.5)',
								margin: '0 0 4px'
							}}
						>
							Numer rezerwacji
						</p>
						<p
							style={{
								fontFamily: 'Playfair Display, serif',
								fontSize: '20px',
								color: '#c4923a',
								margin: 0
							}}
						>
							{booking.ref}
						</p>
					</div>
				</div>

				{/* Tabs */}
				<div
					style={{
						borderBottom: '1px solid rgba(196,146,58,0.15)',
						marginBottom: '40px',
						display: 'flex'
					}}
				>
					<TabBtn id="booking" label="Rezerwacja" />
					<TabBtn id="profile" label="Dane załogi" />
					<TabBtn id="docs" label="Dokumenty" />
				</div>

				{/* Booking tab */}
				{tab === 'booking' && (
					<div>
						{/* Status banner */}
						<div
							style={{
								display: 'flex',
								alignItems: 'center',
								gap: '12px',
								padding: '14px 20px',
								background: 'rgba(80,160,80,0.08)',
								border: '1px solid rgba(80,160,80,0.25)',
								marginBottom: '32px'
							}}
						>
							<div
								style={{
									width: '8px',
									height: '8px',
									background: '#50a050',
									borderRadius: '50%',
									flexShrink: 0
								}}
							/>
							<span
								style={{
									fontFamily: 'DM Sans, sans-serif',
									fontSize: '12px',
									color: 'rgba(245,240,232,0.7)',
									letterSpacing: '0.5px'
								}}
							>
								Rezerwacja potwierdzona · Płatność zrealizowana
							</span>
						</div>

						{/* Voyage card */}
						<div
							style={{
								border: '1px solid rgba(196,146,58,0.2)',
								marginBottom: '32px'
							}}
						>
							<div
								style={{
									padding: '20px 24px',
									background: 'rgba(196,146,58,0.06)',
									borderBottom: '1px solid rgba(196,146,58,0.12)'
								}}
							>
								<p
									style={{
										fontFamily: 'DM Sans, sans-serif',
										fontSize: '10px',
										letterSpacing: '2px',
										textTransform: 'uppercase',
										color: 'rgba(196,146,58,0.6)',
										margin: '0 0 4px'
									}}
								>
									Sail Adventure 2026
								</p>
								<h3
									style={{
										fontFamily: 'Playfair Display, serif',
										fontSize: '22px',
										color: '#f5f0e8',
										margin: 0,
										fontWeight: '400'
									}}
								>
									{booking.seg.name}
								</h3>
							</div>
							<div
								style={{
									display: 'grid',
									gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))'
								}}
							>
								{[
									['Termin', booking.seg.dates],
									['Dni', booking.seg.days],
									['Koja', booking.berth],
									['Kabina', booking.cabin],
									['Pozycja', booking.position],
									['Cena', `${booking.seg.price.toLocaleString('pl-PL')} zł`]
								].map(([k, v]) => (
									<div
										key={k}
										style={{
											padding: '16px 20px',
											borderRight: '1px solid rgba(196,146,58,0.08)',
											borderBottom: '1px solid rgba(196,146,58,0.08)'
										}}
									>
										<p
											style={{
												fontFamily: 'DM Sans, sans-serif',
												fontSize: '9px',
												letterSpacing: '2px',
												textTransform: 'uppercase',
												color: 'rgba(196,146,58,0.45)',
												margin: '0 0 4px'
											}}
										>
											{k}
										</p>
										<p
											style={{
												fontFamily: 'DM Sans, sans-serif',
												fontSize: '14px',
												color: '#f5f0e8',
												margin: 0,
												fontWeight: '500'
											}}
										>
											{v}
										</p>
									</div>
								))}
							</div>
						</div>

						{/* Route timeline */}
						<div style={{ marginBottom: '32px' }}>
							<p
								style={{
									fontFamily: 'DM Sans, sans-serif',
									fontSize: '10px',
									letterSpacing: '2px',
									textTransform: 'uppercase',
									color: 'rgba(196,146,58,0.5)',
									margin: '0 0 16px'
								}}
							>
								Cała trasa rejsu
							</p>
							<div
								style={{
									display: 'flex',
									alignItems: 'center',
									gap: 0,
									overflowX: 'auto',
									paddingBottom: '8px'
								}}
							>
								{[
									{ port: 'Palma de Mallorca', date: '4.10' },
									{ port: 'Gibraltar', date: '11.10', active: true },
									{ port: 'Madera', date: '21.10', active: true },
									{ port: 'Teneryfa', date: '31.10' },
									{ port: 'Cabo Verde', date: '14.11' }
								].map((p, i, arr) => (
									<React.Fragment key={p.port}>
										<div
											style={{
												display: 'flex',
												flexDirection: 'column',
												alignItems: 'center',
												gap: '4px',
												minWidth: '80px'
											}}
										>
											<div
												style={{
													width: '10px',
													height: '10px',
													border: `1.5px solid ${p.active ? '#c4923a' : 'rgba(196,146,58,0.3)'}`,
													background: p.active ? '#c4923a' : 'transparent',
													transform: 'rotate(45deg)',
													flexShrink: 0
												}}
											/>
											<span
												style={{
													fontFamily: 'DM Sans, sans-serif',
													fontSize: '10px',
													color: p.active
														? '#f5f0e8'
														: 'rgba(245,240,232,0.35)',
													textAlign: 'center',
													lineHeight: '1.3'
												}}
											>
												{p.port}
											</span>
											<span
												style={{
													fontFamily: 'DM Sans, sans-serif',
													fontSize: '9px',
													color: p.active ? '#c4923a' : 'rgba(196,146,58,0.3)'
												}}
											>
												{p.date}
											</span>
										</div>
										{i < arr.length - 1 && (
											<div
												style={{
													flex: 1,
													height: '1px',
													background:
														i >= 1 && i <= 2
															? '#c4923a'
															: 'rgba(196,146,58,0.15)',
													minWidth: '24px',
													marginBottom: '30px'
												}}
											/>
										)}
									</React.Fragment>
								))}
							</div>
						</div>

						<div style={{ display: 'flex', gap: '12px' }}>
							<button
								style={{
									padding: '12px 28px',
									background: '#c4923a',
									border: 'none',
									color: '#0d1b2e',
									fontFamily: 'DM Sans, sans-serif',
									fontSize: '11px',
									fontWeight: '700',
									letterSpacing: '2px',
									textTransform: 'uppercase',
									cursor: 'pointer',
									borderRadius: 0
								}}
							>
								↓ Pobierz potwierdzenie
							</button>
							<button
								style={{
									padding: '12px 24px',
									background: 'none',
									border: '1px solid rgba(196,146,58,0.25)',
									color: 'rgba(245,240,232,0.5)',
									fontFamily: 'DM Sans, sans-serif',
									fontSize: '11px',
									letterSpacing: '2px',
									textTransform: 'uppercase',
									cursor: 'pointer',
									borderRadius: 0
								}}
							>
								Kontakt z organizatorem
							</button>
						</div>
					</div>
				)}

				{/* Profile tab */}
				{tab === 'profile' && (
					<div>
						<p
							style={{
								fontFamily: 'DM Sans, sans-serif',
								fontSize: '13px',
								color: 'rgba(245,240,232,0.4)',
								margin: '0 0 32px',
								lineHeight: '1.6'
							}}
						>
							Dane wymagane przez kapitana. Możesz je aktualizować do 30 dni
							przed rejsem.
						</p>
						<div
							style={{
								display: 'grid',
								gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
								gap: '20px',
								maxWidth: '600px'
							}}
						>
							{[
								['Imię i nazwisko', 'Michał Kowalski'],
								['Data urodzenia', '15.03.1985'],
								['Narodowość', 'Polska'],
								['Typ dokumentu', 'Paszport'],
								['Numer dokumentu', 'AB 1234567'],
								['Kontakt alarmowy', 'Anna Kowalska'],
								['Tel. alarmowy', '+48 601 234 567'],
								['Umiejętności pływackie', 'Dobry pływak'],
								['Doświadczenie', 'Kilka rejsów']
							].map(([label, value]) => (
								<div
									key={label}
									style={{
										padding: '14px 16px',
										background: 'rgba(255,255,255,0.03)',
										borderLeft: '2px solid rgba(196,146,58,0.2)'
									}}
								>
									<p
										style={{
											fontFamily: 'DM Sans, sans-serif',
											fontSize: '9px',
											letterSpacing: '2px',
											textTransform: 'uppercase',
											color: 'rgba(196,146,58,0.45)',
											margin: '0 0 4px'
										}}
									>
										{label}
									</p>
									<p
										style={{
											fontFamily: 'DM Sans, sans-serif',
											fontSize: '13px',
											color: '#f5f0e8',
											margin: 0
										}}
									>
										{value}
									</p>
								</div>
							))}
						</div>
						<button
							style={{
								marginTop: '28px',
								padding: '12px 28px',
								background: 'none',
								border: '1px solid rgba(196,146,58,0.35)',
								color: '#c4923a',
								fontFamily: 'DM Sans, sans-serif',
								fontSize: '11px',
								letterSpacing: '2px',
								textTransform: 'uppercase',
								cursor: 'pointer',
								borderRadius: 0
							}}
						>
							Edytuj dane
						</button>
					</div>
				)}

				{/* Docs tab */}
				{tab === 'docs' && (
					<div>
						<p
							style={{
								fontFamily: 'DM Sans, sans-serif',
								fontSize: '13px',
								color: 'rgba(245,240,232,0.4)',
								margin: '0 0 32px'
							}}
						>
							Dokumenty do pobrania
						</p>
						{[
							{
								name: 'Potwierdzenie rezerwacji',
								date: '24.04.2026',
								type: 'PDF'
							},
							{ name: 'Regulamin rejsu', date: '01.01.2026', type: 'PDF' },
							{
								name: 'Lista rzeczy do zabrania',
								date: '01.01.2026',
								type: 'PDF'
							},
							{
								name: 'Plan trasy szczegółowy',
								date: '01.03.2026',
								type: 'PDF'
							}
						].map((doc) => (
							<div
								key={doc.name}
								style={{
									display: 'flex',
									alignItems: 'center',
									justifyContent: 'space-between',
									padding: '16px 20px',
									border: '1px solid rgba(196,146,58,0.12)',
									marginBottom: '8px',
									cursor: 'pointer'
								}}
							>
								<div>
									<p
										style={{
											fontFamily: 'DM Sans, sans-serif',
											fontSize: '13px',
											color: '#f5f0e8',
											margin: '0 0 2px'
										}}
									>
										{doc.name}
									</p>
									<p
										style={{
											fontFamily: 'DM Sans, sans-serif',
											fontSize: '10px',
											color: 'rgba(245,240,232,0.3)',
											margin: 0
										}}
									>
										{doc.type} · {doc.date}
									</p>
								</div>
								<span
									style={{
										fontFamily: 'DM Sans, sans-serif',
										fontSize: '11px',
										color: '#c4923a',
										letterSpacing: '1px'
									}}
								>
									↓
								</span>
							</div>
						))}
					</div>
				)}
			</div>
		</div>
	)
}

Object.assign(window, { Dashboard })
