// docs/design/design_handoff_sailing_architects_new_qa/components/boat-plan.jsx

// BoatPlan — Jeanneau Sun Odyssey 519 architectural floor plan
// Cabin layout per actual SO519 plan:
//   A  — forward island double (dziobowa, łóżko małżeńskie)
//   B  — aft port double (rufowa lewa)
//   C  — aft starboard double (rufowa prawa)
//   D  — mid port, dwa posłania obok siebie (środkowa lewa)
//   E  — mid starboard, ŁÓŻKO PIĘTROWE (środkowa prawa)

const CABINS = [
  { id: 'A', label: 'Kabina A', position: 'Dziobowa · łóżko wyspowe', berths: ['A1','A2'] },
  { id: 'B', label: 'Kabina B', position: 'Rufowa lewa · podwójne', berths: ['B1','B2'] },
  { id: 'C', label: 'Kabina C', position: 'Rufowa prawa · podwójne', berths: ['C1','C2'] },
  { id: 'D', label: 'Kabina D', position: 'Środkowa lewa · dwa single', berths: ['D1','D2'] },
  { id: 'E', label: 'Kabina E', position: 'Środkowa prawa · piętrowe', berths: ['E1','E2'], bunk: true },
];

const TAKEN_BERTHS = new Set(['A2', 'C1', 'D2']);

function BoatPlan({ selectedBerth, onSelectBerth, takenBerths = TAKEN_BERTHS }) {
  const [hovered, setHovered] = React.useState(null);

  function berthState(id) {
    if (takenBerths.has(id)) return 'taken';
    if (selectedBerth === id) return 'selected';
    if (hovered === id) return 'hovered';
    return 'available';
  }

  function berthFill(id) {
    const s = berthState(id);
    if (s === 'taken') return 'rgba(13,27,46,0.65)';
    if (s === 'selected') return 'rgba(196,146,58,0.85)';
    if (s === 'hovered') return 'rgba(196,146,58,0.25)';
    return 'rgba(245,240,232,0.10)';
  }

  function berthStroke(id) {
    const s = berthState(id);
    if (s === 'taken') return '#3a4a5c';
    if (s === 'selected') return '#c4923a';
    return '#c4923a';
  }

  function handleBerth(id) {
    if (takenBerths.has(id)) return;
    onSelectBerth(selectedBerth === id ? null : id);
  }

  // Standard berth rectangle
  function BerthRect({ id, x, y, w, h, labelX, labelY }) {
    const state = berthState(id);
    const clickable = !takenBerths.has(id);
    return (
      <g
        onClick={() => handleBerth(id)}
        onMouseEnter={() => setHovered(id)}
        onMouseLeave={() => setHovered(null)}
        style={{ cursor: clickable ? 'pointer' : 'not-allowed' }}
      >
        <rect x={x} y={y} width={w} height={h}
          fill={berthFill(id)}
          stroke={berthStroke(id)}
          strokeWidth={state === 'selected' ? 1.5 : 0.8}
        />
        {state === 'taken' && (
          <line x1={x+4} y1={y+4} x2={x+w-4} y2={y+h-4} stroke="#3a4a5c" strokeWidth="0.8" />
        )}
        {state === 'selected' && (
          <>
            <line x1={(labelX??x+w/2)-4} y1={labelY??y+h/2} x2={(labelX??x+w/2)+4} y2={labelY??y+h/2} stroke="#fff" strokeWidth="1.2" />
            <line x1={labelX??x+w/2} y1={(labelY??y+h/2)-4} x2={labelX??x+w/2} y2={(labelY??y+h/2)+4} stroke="#fff" strokeWidth="1.2" />
          </>
        )}
        <text x={labelX??x+w/2} y={labelY??y+h/2}
          textAnchor="middle" dominantBaseline="central"
          fontSize="7" fontFamily="DM Sans, sans-serif"
          fill={state === 'selected' ? '#fff' : state === 'taken' ? '#3a4a5c' : '#c4923a'}
          fontWeight="600" letterSpacing="0.5"
        >{id}</text>
      </g>
    );
  }

  // Bunk bed — E1 upper (dashed overlay), E2 lower (solid base)
  // Displayed as one stacked unit, both clickable separately
  function BunkBed({ x, y, w, h }) {
    const stateE2 = berthState('E2'); // lower — solid
    const stateE1 = berthState('E1'); // upper — dashed overlay

    // Hit zones: lower = bottom half, upper = top half (or just two rows)
    const rowH = h / 2;

    return (
      <g>
        {/* ── LOWER BERTH E2 ── */}
        <g
          onClick={() => handleBerth('E2')}
          onMouseEnter={() => setHovered('E2')}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has('E2') ? 'not-allowed' : 'pointer' }}
        >
          <rect x={x} y={y+rowH} width={w} height={rowH}
            fill={berthFill('E2')}
            stroke={berthStroke('E2')}
            strokeWidth={stateE2 === 'selected' ? 1.5 : 0.8}
          />
          {stateE2 === 'taken' && <line x1={x+4} y1={y+rowH+4} x2={x+w-4} y2={y+h-4} stroke="#3a4a5c" strokeWidth="0.8" />}
          {stateE2 === 'selected' && (
            <>
              <line x1={x+w/2-4} y1={y+rowH+rowH/2} x2={x+w/2+4} y2={y+rowH+rowH/2} stroke="#fff" strokeWidth="1.2" />
              <line x1={x+w/2} y1={y+rowH+rowH/2-4} x2={x+w/2} y2={y+rowH+rowH/2+4} stroke="#fff" strokeWidth="1.2" />
            </>
          )}
          <text x={x+w/2} y={y+rowH+rowH/2}
            textAnchor="middle" dominantBaseline="central"
            fontSize="6.5" fontFamily="DM Sans, sans-serif"
            fill={stateE2 === 'selected' ? '#fff' : stateE2 === 'taken' ? '#3a4a5c' : '#c4923a'}
            fontWeight="600"
          >E2</text>
          {/* "dół" label */}
          <text x={x+w-3} y={y+rowH+rowH/2}
            textAnchor="end" dominantBaseline="central"
            fontSize="4" fontFamily="DM Sans, sans-serif"
            fill="rgba(196,146,58,0.4)" letterSpacing="0.3"
          >dół</text>
        </g>

        {/* ── UPPER BERTH E1 — dashed border + hatch ── */}
        <g
          onClick={() => handleBerth('E1')}
          onMouseEnter={() => setHovered('E1')}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has('E1') ? 'not-allowed' : 'pointer' }}
        >
          {/* Hatch fill indicating upper bunk */}
          <defs>
            <pattern id="bunk-hatch" patternUnits="userSpaceOnUse" width="5" height="5" patternTransform="rotate(45)">
              <line x1="0" y1="0" x2="0" y2="5"
                stroke={stateE1 === 'selected' ? 'rgba(255,255,255,0.4)' : stateE1 === 'taken' ? 'rgba(58,74,92,0.4)' : 'rgba(196,146,58,0.18)'}
                strokeWidth="1" />
            </pattern>
          </defs>
          <rect x={x} y={y} width={w} height={rowH}
            fill={stateE1 === 'selected' ? 'rgba(196,146,58,0.75)' : stateE1 === 'taken' ? 'rgba(13,27,46,0.55)' : 'url(#bunk-hatch)'}
          />
          {/* Dashed border for upper bunk */}
          <rect x={x} y={y} width={w} height={rowH}
            fill="none"
            stroke={berthStroke('E1')}
            strokeWidth={stateE1 === 'selected' ? 1.5 : 0.8}
            strokeDasharray={stateE1 === 'selected' ? 'none' : '3 2'}
          />
          {stateE1 === 'taken' && <line x1={x+4} y1={y+4} x2={x+w-4} y2={y+rowH-4} stroke="#3a4a5c" strokeWidth="0.8" />}
          {stateE1 === 'selected' && (
            <>
              <line x1={x+w/2-4} y1={y+rowH/2} x2={x+w/2+4} y2={y+rowH/2} stroke="#fff" strokeWidth="1.2" />
              <line x1={x+w/2} y1={y+rowH/2-4} x2={x+w/2} y2={y+rowH/2+4} stroke="#fff" strokeWidth="1.2" />
            </>
          )}
          <text x={x+w/2} y={y+rowH/2}
            textAnchor="middle" dominantBaseline="central"
            fontSize="6.5" fontFamily="DM Sans, sans-serif"
            fill={stateE1 === 'selected' ? '#fff' : stateE1 === 'taken' ? '#3a4a5c' : '#c4923a'}
            fontWeight="600"
          >E1</text>
          {/* "góra" label */}
          <text x={x+w-3} y={y+rowH/2}
            textAnchor="end" dominantBaseline="central"
            fontSize="4" fontFamily="DM Sans, sans-serif"
            fill="rgba(196,146,58,0.4)" letterSpacing="0.3"
          >góra</text>
        </g>

        {/* ── LADDER symbol — left edge of bunk unit ── */}
        <g opacity="0.5">
          {/* Ladder rails */}
          <line x1={x-1} y1={y+4} x2={x-1} y2={y+h-4} stroke="#c4923a" strokeWidth="0.7" />
          <line x1={x+4} y1={y+4} x2={x+4} y2={y+h-4} stroke="#c4923a" strokeWidth="0.7" />
          {/* Ladder rungs */}
          {[0.2, 0.4, 0.6, 0.8].map((t, i) => (
            <line key={i} x1={x-1} y1={y+h*t} x2={x+4} y2={y+h*t} stroke="#c4923a" strokeWidth="0.6" />
          ))}
        </g>

        {/* Separator line between bunks */}
        <line x1={x} y1={y+rowH} x2={x+w} y2={y+rowH} stroke="#c4923a" strokeWidth="0.5" />
      </g>
    );
  }

  // Island double bed (Kabina A) — single wide berth with rounded head
  function IslandBed({ x, y, w, h, id1, id2 }) {
    // A1 = left side, A2 = right side of the island bed
    const midX = x + w / 2;
    return (
      <g>
        {/* Bed outline */}
        <rect x={x} y={y} width={w} height={h}
          fill="rgba(245,240,232,0.06)"
          stroke="rgba(196,146,58,0.3)"
          strokeWidth="0.6"
        />
        {/* Pillow row at top */}
        <rect x={x+4} y={y+3} width={w/2-8} height={10}
          fill={berthFill(id1)} stroke={berthStroke(id1)} strokeWidth="0.7" rx="1"
          onClick={() => handleBerth(id1)}
          onMouseEnter={() => setHovered(id1)}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has(id1) ? 'not-allowed' : 'pointer' }}
        />
        <rect x={midX+4} y={y+3} width={w/2-8} height={10}
          fill={berthFill(id2)} stroke={berthStroke(id2)} strokeWidth="0.7" rx="1"
          onClick={() => handleBerth(id2)}
          onMouseEnter={() => setHovered(id2)}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has(id2) ? 'not-allowed' : 'pointer' }}
        />
        {/* Main bed surface — two click zones */}
        <rect x={x+2} y={y+16} width={w/2-4} height={h-20}
          fill={berthFill(id1)} stroke={berthStroke(id1)} strokeWidth="0.8"
          onClick={() => handleBerth(id1)}
          onMouseEnter={() => setHovered(id1)}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has(id1) ? 'not-allowed' : 'pointer' }}
        />
        <rect x={midX+2} y={y+16} width={w/2-4} height={h-20}
          fill={berthFill(id2)} stroke={berthStroke(id2)} strokeWidth="0.8"
          onClick={() => handleBerth(id2)}
          onMouseEnter={() => setHovered(id2)}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has(id2) ? 'not-allowed' : 'pointer' }}
        />
        {/* Center walkway divider */}
        <line x1={midX} y1={y} x2={midX} y2={y+h} stroke="rgba(196,146,58,0.2)" strokeWidth="0.5" strokeDasharray="2 2" />
        {/* Labels */}
        <text x={x+w/4} y={y+h/2+6} textAnchor="middle" dominantBaseline="central"
          fontSize="7" fontFamily="DM Sans, sans-serif"
          fill={berthState(id1)==='selected'?'#fff':berthState(id1)==='taken'?'#3a4a5c':'#c4923a'}
          fontWeight="600">{id1}</text>
        <text x={x+3*w/4} y={y+h/2+6} textAnchor="middle" dominantBaseline="central"
          fontSize="7" fontFamily="DM Sans, sans-serif"
          fill={berthState(id2)==='selected'?'#fff':berthState(id2)==='taken'?'#3a4a5c':'#c4923a'}
          fontWeight="600">{id2}</text>
        {/* Taken overlays */}
        {berthState(id1)==='taken' && <line x1={x+4} y1={y+16} x2={midX-2} y2={y+h-2} stroke="#3a4a5c" strokeWidth="0.8" />}
        {berthState(id2)==='taken' && <line x1={midX+4} y1={y+16} x2={x+w-4} y2={y+h-2} stroke="#3a4a5c" strokeWidth="0.8" />}
        {/* Selected markers */}
        {berthState(id1)==='selected' && <>
          <line x1={x+w/4-4} y1={y+h/2+6} x2={x+w/4+4} y2={y+h/2+6} stroke="#fff" strokeWidth="1.2" />
          <line x1={x+w/4} y1={y+h/2+2} x2={x+w/4} y2={y+h/2+10} stroke="#fff" strokeWidth="1.2" />
        </>}
        {berthState(id2)==='selected' && <>
          <line x1={x+3*w/4-4} y1={y+h/2+6} x2={x+3*w/4+4} y2={y+h/2+6} stroke="#fff" strokeWidth="1.2" />
          <line x1={x+3*w/4} y1={y+h/2+2} x2={x+3*w/4} y2={y+h/2+10} stroke="#fff" strokeWidth="1.2" />
        </>}
      </g>
    );
  }

  // Double berth (B, C) — wide single rectangle split into two click zones
  function DoubleBerth({ x, y, w, h, id1, id2, split = 'v' }) {
    // split='h' = horizontal split (left/right), split='v' = vertical (top/bottom)
    const isH = split === 'h';
    const midX = x + w / 2;
    const midY = y + h / 2;
    return (
      <g>
        <rect x={x} y={y} width={w} height={h}
          fill="rgba(245,240,232,0.04)" stroke="rgba(196,146,58,0.2)" strokeWidth="0.5" />

        {/* Zone 1 */}
        <rect
          x={x} y={y}
          width={isH ? w/2 : w}
          height={isH ? h : h/2}
          fill={berthFill(id1)} stroke={berthStroke(id1)} strokeWidth="0.8"
          onClick={() => handleBerth(id1)}
          onMouseEnter={() => setHovered(id1)}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has(id1) ? 'not-allowed' : 'pointer' }}
        />
        {berthState(id1)==='taken' && <line x1={x+3} y1={y+3} x2={isH?midX-3:x+w-3} y2={isH?y+h-3:midY-3} stroke="#3a4a5c" strokeWidth="0.8" />}
        {berthState(id1)==='selected' && <>
          <line x1={isH?x+w/4-4:x+w/2-4} y1={isH?y+h/2:y+h/4} x2={isH?x+w/4+4:x+w/2+4} y2={isH?y+h/2:y+h/4} stroke="#fff" strokeWidth="1.2" />
          <line x1={isH?x+w/4:x+w/2} y1={isH?y+h/2-4:y+h/4-4} x2={isH?x+w/4:x+w/2} y2={isH?y+h/2+4:y+h/4+4} stroke="#fff" strokeWidth="1.2" />
        </>}
        <text
          x={isH ? x+w/4 : x+w/2}
          y={isH ? y+h/2 : y+h/4}
          textAnchor="middle" dominantBaseline="central"
          fontSize="7" fontFamily="DM Sans, sans-serif"
          fill={berthState(id1)==='selected'?'#fff':berthState(id1)==='taken'?'#3a4a5c':'#c4923a'}
          fontWeight="600"
        >{id1}</text>

        {/* Zone 2 */}
        <rect
          x={isH ? midX : x}
          y={isH ? y : midY}
          width={isH ? w/2 : w}
          height={isH ? h : h/2}
          fill={berthFill(id2)} stroke={berthStroke(id2)} strokeWidth="0.8"
          onClick={() => handleBerth(id2)}
          onMouseEnter={() => setHovered(id2)}
          onMouseLeave={() => setHovered(null)}
          style={{ cursor: takenBerths.has(id2) ? 'not-allowed' : 'pointer' }}
        />
        {berthState(id2)==='taken' && <line x1={isH?midX+3:x+3} y1={isH?y+3:midY+3} x2={x+w-3} y2={y+h-3} stroke="#3a4a5c" strokeWidth="0.8" />}
        {berthState(id2)==='selected' && <>
          <line x1={isH?x+3*w/4-4:x+w/2-4} y1={isH?y+h/2:y+3*h/4} x2={isH?x+3*w/4+4:x+w/2+4} y2={isH?y+h/2:y+3*h/4} stroke="#fff" strokeWidth="1.2" />
          <line x1={isH?x+3*w/4:x+w/2} y1={isH?y+h/2-4:y+3*h/4-4} x2={isH?x+3*w/4:x+w/2} y2={isH?y+h/2+4:y+3*h/4+4} stroke="#fff" strokeWidth="1.2" />
        </>}
        <text
          x={isH ? x+3*w/4 : x+w/2}
          y={isH ? y+h/2 : y+3*h/4}
          textAnchor="middle" dominantBaseline="central"
          fontSize="7" fontFamily="DM Sans, sans-serif"
          fill={berthState(id2)==='selected'?'#fff':berthState(id2)==='taken'?'#3a4a5c':'#c4923a'}
          fontWeight="600"
        >{id2}</text>

        {/* Divider */}
        {isH
          ? <line x1={midX} y1={y} x2={midX} y2={y+h} stroke="rgba(196,146,58,0.25)" strokeWidth="0.5" strokeDasharray="2 2" />
          : <line x1={x} y1={midY} x2={x+w} y2={midY} stroke="rgba(196,146,58,0.25)" strokeWidth="0.5" strokeDasharray="2 2" />
        }
      </g>
    );
  }

  return (
    <div style={{ display: 'flex', gap: '32px', alignItems: 'flex-start', justifyContent: 'center', flexWrap: 'wrap' }}>
      {/* ── SVG PLAN ── */}
      <div style={{ position: 'relative' }}>
        <svg viewBox="0 0 210 540" width="210" height="540" style={{ display: 'block' }}>
          <defs>
            <pattern id="grid" patternUnits="userSpaceOnUse" width="10" height="10">
              <path d="M 10 0 L 0 0 0 10" fill="none" stroke="rgba(196,146,58,0.06)" strokeWidth="0.5" />
            </pattern>
          </defs>
          <rect width="210" height="540" fill="url(#grid)" />

          {/* ── HULL ── */}
          <path
            d="M 105 10
               C 145 20, 192 82, 196 175
               L 196 378
               C 196 438, 170 478, 140 496
               L 70 496
               C 40 478, 14 438, 14 378
               L 14 175
               C 18 82, 65 20, 105 10 Z"
            fill="none" stroke="#c4923a" strokeWidth="1.5"
          />

          {/* Centerline */}
          <line x1="105" y1="10" x2="105" y2="496" stroke="rgba(196,146,58,0.15)" strokeWidth="0.5" strokeDasharray="4 3" />

          {/* ── DZIÓB label ── */}
          <text x="105" y="24" textAnchor="middle" fontSize="5.5" fontFamily="DM Sans" fill="rgba(196,146,58,0.5)" letterSpacing="2">DZIÓB</text>

          {/* ── KABINA A — island double, forward ── */}
          {/* Bulkhead forward at y=52 (narrow hull) */}
          <text x="105" y="54" textAnchor="middle" fontSize="6" fontFamily="DM Sans" fill="rgba(196,146,58,0.45)" fontWeight="700" letterSpacing="1">A</text>
          {/* Island bed centered */}
          <IslandBed x={38} y={62} w={134} h={72} id1="A1" id2="A2" />
          {/* Walkway sides annotation */}
          <text x="26" y="98" textAnchor="middle" fontSize="4" fontFamily="DM Sans" fill="rgba(196,146,58,0.2)" transform="rotate(-90 26 98)">przejście</text>
          <text x="184" y="98" textAnchor="middle" fontSize="4" fontFamily="DM Sans" fill="rgba(196,146,58,0.2)" transform="rotate(90 184 98)">przejście</text>

          {/* Bulkhead at y=140 */}
          <line x1="26" y1="140" x2="184" y2="140" stroke="#c4923a" strokeWidth="0.8" />

          {/* ── SALON / SALOON ── */}
          <text x="105" y="155" textAnchor="middle" fontSize="5.5" fontFamily="DM Sans" fill="rgba(196,146,58,0.35)" letterSpacing="2">SALON</text>
          {/* Port settee */}
          <rect x="16" y="160" width="42" height="52" fill="none" stroke="rgba(196,146,58,0.15)" strokeWidth="0.6" />
          {/* Starboard settee */}
          <rect x="152" y="160" width="42" height="52" fill="none" stroke="rgba(196,146,58,0.15)" strokeWidth="0.6" />
          {/* Table */}
          <rect x="72" y="166" width="66" height="40" fill="none" stroke="rgba(196,146,58,0.2)" strokeWidth="0.6" />
          {/* Galley port */}
          <rect x="16" y="215" width="42" height="28" fill="none" stroke="rgba(196,146,58,0.12)" strokeWidth="0.5" />
          <text x="37" y="230" textAnchor="middle" fontSize="4" fontFamily="DM Sans" fill="rgba(196,146,58,0.25)" letterSpacing="1">GALLEY</text>
          {/* Nav station starboard */}
          <rect x="152" y="215" width="42" height="22" fill="none" stroke="rgba(196,146,58,0.12)" strokeWidth="0.5" />
          <text x="173" y="228" textAnchor="middle" fontSize="4" fontFamily="DM Sans" fill="rgba(196,146,58,0.25)" letterSpacing="1">NAV</text>

          {/* Companionway */}
          <rect x="76" y="247" width="58" height="9" fill="rgba(13,27,46,0.5)" stroke="rgba(196,146,58,0.3)" strokeWidth="0.6" />
          <text x="105" y="253.5" textAnchor="middle" fontSize="4" fontFamily="DM Sans" fill="rgba(196,146,58,0.5)" letterSpacing="1">ZEJŚCIE</text>

          {/* Bulkhead at y=262 */}
          <line x1="14" y1="262" x2="196" y2="262" stroke="#c4923a" strokeWidth="0.9" />

          {/* ── MID CABINS D (port) & E (starboard) ── */}
          {/* Center divider */}
          <line x1="105" y1="262" x2="105" y2="382" stroke="#c4923a" strokeWidth="0.8" />
          {/* Bulkhead at y=382 */}
          <line x1="14" y1="382" x2="196" y2="382" stroke="#c4923a" strokeWidth="0.9" />

          {/* KABINA D — port mid, dwa single obok siebie (fore/aft) */}
          <text x="59" y="274" textAnchor="middle" fontSize="6" fontFamily="DM Sans" fill="rgba(196,146,58,0.45)" fontWeight="700" letterSpacing="1">D</text>
          <DoubleBerth x={16} y={282} w={87} h={92} id1="D1" id2="D2" split="v" />

          {/* KABINA E — starboard mid, PIĘTROWE */}
          <text x="151" y="274" textAnchor="middle" fontSize="6" fontFamily="DM Sans" fill="rgba(196,146,58,0.45)" fontWeight="700" letterSpacing="1">E</text>
          {/* "piętrowe" badge */}
          <text x="164" y="274" textAnchor="middle" fontSize="4" fontFamily="DM Sans" fill="rgba(196,146,58,0.55)" letterSpacing="0.5">piętrowe</text>
          <BunkBed x={107} y={282} w={87} h={92} />

          {/* ── AFT CABINS B (port) & C (starboard) ── */}
          {/* Center divider */}
          <line x1="105" y1="382" x2="105" y2="495" stroke="#c4923a" strokeWidth="0.8" />

          {/* KABINA B — port aft, double */}
          <text x="59" y="393" textAnchor="middle" fontSize="6" fontFamily="DM Sans" fill="rgba(196,146,58,0.45)" fontWeight="700" letterSpacing="1">B</text>
          <DoubleBerth x={16} y={400} w={87} h={87} id1="B1" id2="B2" split="v" />

          {/* KABINA C — starboard aft, double */}
          <text x="151" y="393" textAnchor="middle" fontSize="6" fontFamily="DM Sans" fill="rgba(196,146,58,0.45)" fontWeight="700" letterSpacing="1">C</text>
          <DoubleBerth x={107} y={400} w={87} h={87} id1="C1" id2="C2" split="v" />

          {/* RUFA label */}
          <text x="105" y="510" textAnchor="middle" fontSize="5.5" fontFamily="DM Sans" fill="rgba(196,146,58,0.4)" letterSpacing="2">RUFA</text>

          {/* Title */}
          <text x="105" y="527" textAnchor="middle" fontSize="4.5" fontFamily="DM Sans" fill="rgba(196,146,58,0.25)" letterSpacing="1">JEANNEAU SUN ODYSSEY 519 · rzut kojowy</text>
        </svg>
      </div>

      {/* ── LEGEND + CABIN LIST ── */}
      <div style={{ minWidth: '230px', maxWidth: '290px' }}>

        {/* Legend */}
        <p style={{ fontFamily: 'DM Sans, sans-serif', fontSize: '11px', letterSpacing: '2px', color: 'rgba(196,146,58,0.7)', textTransform: 'uppercase', marginBottom: '12px' }}>Legenda</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '24px' }}>
          {[
            { bg: 'rgba(245,240,232,0.10)', border: '#c4923a', dash: false, label: 'Dostępna koja' },
            { bg: 'rgba(196,146,58,0.85)', border: '#c4923a', dash: false, label: 'Wybrana koja' },
            { bg: 'rgba(13,27,46,0.55)', border: '#3a4a5c', dash: false, label: 'Zajęta koja' },
            { bg: 'rgba(196,146,58,0.08)', border: '#c4923a', dash: true, label: 'Koja górna (piętrowa)' },
          ].map(item => (
            <div key={item.label} style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <div style={{ width: '22px', height: '13px', background: item.bg, border: `1px ${item.dash ? 'dashed' : 'solid'} ${item.border}`, flexShrink: 0 }} />
              <span style={{ fontFamily: 'DM Sans, sans-serif', fontSize: '12px', color: 'rgba(245,240,232,0.6)' }}>{item.label}</span>
            </div>
          ))}
        </div>

        {/* Cabin list */}
        <p style={{ fontFamily: 'DM Sans, sans-serif', fontSize: '11px', letterSpacing: '2px', color: 'rgba(196,146,58,0.7)', textTransform: 'uppercase', marginBottom: '12px' }}>Kajuty</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
          {CABINS.map(cabin => (
            <div key={cabin.id} style={{ padding: '8px 12px', background: 'rgba(255,255,255,0.04)', borderLeft: `2px solid ${cabin.bunk ? '#c4923a' : 'rgba(196,146,58,0.3)'}` }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div>
                  <span style={{ fontFamily: 'Playfair Display, serif', fontSize: '13px', color: 'rgba(245,240,232,0.9)', fontWeight: '600' }}>
                    {cabin.label}
                    {cabin.bunk && <span style={{ fontFamily: 'DM Sans, sans-serif', fontSize: '9px', color: '#c4923a', letterSpacing: '1px', marginLeft: '6px', textTransform: 'uppercase', verticalAlign: 'middle' }}>piętrowe</span>}
                  </span>
                  <span style={{ display: 'block', fontFamily: 'DM Sans, sans-serif', fontSize: '10px', color: 'rgba(245,240,232,0.4)', marginTop: '1px' }}>{cabin.position}</span>
                </div>
                <div style={{ display: 'flex', gap: '4px' }}>
                  {cabin.berths.map((b, bi) => {
                    const state = berthState(b);
                    const isUpper = cabin.bunk && bi === 0;
                    return (
                      <div key={b} onClick={() => handleBerth(b)} style={{
                        width: '32px', height: '24px',
                        background: state === 'selected' ? '#c4923a' : state === 'taken' ? 'rgba(13,27,46,0.5)' : 'transparent',
                        border: `${isUpper ? 'dashed' : 'solid'} 1px ${state === 'taken' ? '#3a4a5c' : '#c4923a'}`,
                        display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column',
                        cursor: state === 'taken' ? 'not-allowed' : 'pointer',
                        fontFamily: 'DM Sans, sans-serif', fontSize: '9px', fontWeight: '700',
                        color: state === 'selected' ? '#fff' : state === 'taken' ? '#3a4a5c' : '#c4923a',
                        transition: 'all 0.15s ease',
                        gap: '1px',
                      }}>
                        <span>{b}</span>
                        {cabin.bunk && <span style={{ fontSize: '5px', opacity: 0.7, letterSpacing: 0 }}>{bi === 0 ? 'góra' : 'dół'}</span>}
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Selected berth info */}
        {selectedBerth && (
          <div style={{ marginTop: '16px', padding: '14px 16px', background: 'rgba(196,146,58,0.12)', border: '1px solid rgba(196,146,58,0.4)' }}>
            <p style={{ fontFamily: 'DM Sans, sans-serif', fontSize: '10px', letterSpacing: '2px', color: '#c4923a', textTransform: 'uppercase', margin: '0 0 4px' }}>Wybrana</p>
            <p style={{ fontFamily: 'Playfair Display, serif', fontSize: '18px', color: '#f5f0e8', margin: '0 0 2px' }}>Koja {selectedBerth}</p>
            <p style={{ fontFamily: 'DM Sans, sans-serif', fontSize: '11px', color: 'rgba(245,240,232,0.5)', margin: 0 }}>
              {CABINS.find(c => c.berths.includes(selectedBerth))?.label}
              {' · '}
              {CABINS.find(c => c.berths.includes(selectedBerth))?.bunk
                ? (selectedBerth.endsWith('1') ? 'koja górna' : 'koja dolna')
                : CABINS.find(c => c.berths.includes(selectedBerth))?.position
              }
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

Object.assign(window, { BoatPlan, CABINS, TAKEN_BERTHS });

// src/lib/components/boat-plan/boat-plan.svelte
<script lang="ts">
	import { cabins, findCabinByBerth } from '$lib/data/cabins'

	type BerthStatus = 'taken' | 'captain' | 'complimentary'
	type BerthState =
		| 'available'
		| 'hovered'
		| 'selected'
		| 'taken'
		| 'captain'
		| 'complimentary'

	type Props = {
		selectedBerth: string | null
		onSelectBerth: (id: string | null) => void
		berthStatuses?: ReadonlyMap<string, BerthStatus>
	}

	let {
		selectedBerth,
		onSelectBerth,
		berthStatuses = new Map<string, BerthStatus>([
			['A2', 'taken'],
			['C1', 'captain'],
			['D2', 'taken']
		])
	}: Props = $props()

	let hovered = $state<string | null>(null)

	function berthState(id: string): BerthState {
		const status = berthStatuses.get(id)
		if (status) return status
		if (selectedBerth === id) return 'selected'
		if (hovered === id) return 'hovered'
		return 'available'
	}

	function berthFill(id: string): string {
		switch (berthState(id)) {
			case 'taken':
				return 'rgba(13,27,46,0.55)'
			case 'captain':
				return 'rgba(8,18,36,0.92)'
			case 'complimentary':
				return 'rgba(196,146,58,0.06)'
			case 'selected':
				return 'rgba(196,146,58,0.85)'
			case 'hovered':
				return 'rgba(196,146,58,0.22)'
			default:
				return 'rgba(245,240,232,0.12)'
		}
	}

	function berthStroke(id: string): string {
		switch (berthState(id)) {
			case 'taken':
				return '#3a4a5c'
			case 'captain':
				return 'rgba(196,146,58,0.5)'
			case 'complimentary':
				return 'rgba(196,146,58,0.35)'
			default:
				return '#c4923a'
		}
	}

	function berthLabelColor(id: string): string {
		switch (berthState(id)) {
			case 'selected':
				return '#fff'
			case 'taken':
				return '#3a4a5c'
			case 'captain':
				return 'rgba(196,146,58,0.5)'
			case 'complimentary':
				return 'rgba(196,146,58,0.4)'
			default:
				return '#c4923a'
		}
	}

	function handleBerth(id: string) {
		if (berthStatuses.has(id)) return
		onSelectBerth(selectedBerth === id ? null : id)
	}

	function handleKey(e: KeyboardEvent, id: string) {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault()
			handleBerth(id)
		}
	}

	// Berth rectangles computed from design SVG (viewBox 0 0 420 1080)
	// Forward section (A = port, B = starboard): 4 berths side-by-side pairs
	// Middle section (E): bunk-bed cabin, E1 lower / E2 upper
	// Aft section (C = port, D = starboard): 4 berths in two pairs
	const berthSlots = [
		{ id: 'A1', x: 80, y: 126, w: 59, h: 138 },
		{ id: 'A2', x: 147, y: 126, w: 59, h: 138 },
		{ id: 'B1', x: 214, y: 126, w: 59, h: 138 },
		{ id: 'B2', x: 281, y: 126, w: 59, h: 138 },
		{ id: 'E1', x: 228, y: 587, w: 68, h: 172 },
		{ id: 'E2', x: 322, y: 585, w: 66, h: 174 },
		{ id: 'C1', x: 59, y: 798, w: 69, h: 150 },
		{ id: 'C2', x: 137, y: 798, w: 69, h: 150 },
		{ id: 'D1', x: 214, y: 798, w: 69, h: 150 },
		{ id: 'D2', x: 292, y: 798, w: 69, h: 150 }
	] as const

	const legend = [
		{ fill: 'rgba(245,240,232,0.12)', stroke: '#c4923a', label: 'Dostępna' },
		{ fill: 'rgba(196,146,58,0.85)', stroke: '#c4923a', label: 'Wybrana' },
		{ fill: 'rgba(13,27,46,0.55)', stroke: '#3a4a5c', label: 'Zajęta' },
		{
			fill: 'rgba(8,18,36,0.92)',
			stroke: 'rgba(196,146,58,0.5)',
			label: 'Kapitan ⚓'
		},
		{
			fill: 'rgba(196,146,58,0.06)',
			stroke: 'rgba(196,146,58,0.35)',
			label: 'Bezpłatna'
		}
	]

	const selectedCabin = $derived(
		selectedBerth ? findCabinByBerth(selectedBerth) : undefined
	)
</script>

<div class="boat">
	<div class="boat__svg-wrap">
		<svg
			viewBox="0 0 420 1080"
			width="210"
			height="540"
			class="boat__svg"
			xmlns="http://www.w3.org/2000/svg"
		>
			<!-- Hull outline (all coords at 2× design scale) -->
			<path
				d="M210,20 C290,40 384,164 392,350 L392,756 C392,876 340,956 280,992 L140,992 C80,956 28,876 28,756 L28,350 C36,164 130,40 210,20Z"
				fill="rgba(13,27,46,0.55)"
				stroke="#c4923a"
				stroke-width="3"
			/>

			<!-- Centreline (dashed) -->
			<line
				x1="210"
				y1="20"
				x2="210"
				y2="992"
				stroke="rgba(196,146,58,0.18)"
				stroke-width="1"
				stroke-dasharray="8 6"
			/>

			<!-- ── BOW ── -->
			<text
				x="210"
				y="56"
				text-anchor="middle"
				font-size="11"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.6)"
				letter-spacing="4">DZIÓB</text
			>

			<!-- Forward cabin: shared outer border -->
			<rect
				x="76"
				y="124"
				width="268"
				height="144"
				fill="rgba(245,240,232,0.04)"
				stroke="rgba(196,146,58,0.22)"
				stroke-width="1.2"
			/>

			<!-- Forward cabin: inner centreline divider -->
			<line
				x1="210"
				y1="124"
				x2="210"
				y2="268"
				stroke="rgba(196,146,58,0.22)"
				stroke-width="1"
				stroke-dasharray="4 4"
			/>

			<!-- Forward section labels -->
			<text
				x="138"
				y="112"
				text-anchor="middle"
				font-size="13"
				font-family="DM Sans"
				font-weight="700"
				fill="rgba(196,146,58,0.6)">A</text
			>
			<text
				x="282"
				y="112"
				text-anchor="middle"
				font-size="13"
				font-family="DM Sans"
				font-weight="700"
				fill="rgba(196,146,58,0.6)">B</text
			>

			<!-- Separator: forward cabin → salon -->
			<line
				x1="52"
				y1="280"
				x2="368"
				y2="280"
				stroke="#c4923a"
				stroke-width="1.6"
			/>

			<!-- ── SALON ── -->
			<text
				x="210"
				y="316"
				text-anchor="middle"
				font-size="11"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.32)"
				letter-spacing="4">SALON</text
			>

			<!-- Salon settees (port + starboard) -->
			<rect
				x="32"
				y="320"
				width="84"
				height="104"
				fill="none"
				stroke="rgba(196,146,58,0.14)"
				stroke-width="1.2"
			/>
			<rect
				x="304"
				y="320"
				width="84"
				height="104"
				fill="none"
				stroke="rgba(196,146,58,0.14)"
				stroke-width="1.2"
			/>
			<!-- Salon table -->
			<rect
				x="144"
				y="332"
				width="132"
				height="80"
				fill="none"
				stroke="rgba(196,146,58,0.2)"
				stroke-width="1.2"
			/>

			<!-- NAV station -->
			<rect
				x="304"
				y="330"
				width="84"
				height="44"
				fill="none"
				stroke="rgba(196,146,58,0.12)"
				stroke-width="1"
			/>
			<text
				x="346"
				y="356"
				text-anchor="middle"
				font-size="9"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.28)"
				letter-spacing="2">NAV</text
			>

			<!-- Galley -->
			<rect
				x="32"
				y="430"
				width="84"
				height="56"
				fill="none"
				stroke="rgba(196,146,58,0.12)"
				stroke-width="1"
			/>
			<text
				x="74"
				y="462"
				text-anchor="middle"
				font-size="9"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.28)"
				letter-spacing="1">GALLEY</text
			>

			<!-- Companionway hatch -->
			<rect
				x="152"
				y="494"
				width="116"
				height="18"
				fill="rgba(13,27,46,0.8)"
				stroke="rgba(196,146,58,0.4)"
				stroke-width="1.2"
			/>
			<text
				x="210"
				y="507"
				text-anchor="middle"
				font-size="8"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.6)"
				letter-spacing="2">ZEJŚCIE</text
			>

			<!-- Separator: salon → middle cabins -->
			<line
				x1="28"
				y1="524"
				x2="392"
				y2="524"
				stroke="#c4923a"
				stroke-width="1.8"
			/>

			<!-- Middle section centreline -->
			<line
				x1="210"
				y1="524"
				x2="210"
				y2="764"
				stroke="#c4923a"
				stroke-width="1.6"
			/>

			<!-- E section label -->
			<text
				x="289"
				y="564"
				text-anchor="middle"
				font-size="13"
				font-family="DM Sans"
				font-weight="700"
				fill="rgba(196,146,58,0.6)">E</text
			>
			<text
				x="323"
				y="580"
				text-anchor="middle"
				font-size="9"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.65)">piętrowe</text
			>

			<!-- E2 upper-bunk outline (dashed overlay, shown when not selected/taken) -->
			<rect
				x="322"
				y="585"
				width="66"
				height="174"
				fill="none"
				stroke="rgba(196,146,58,0.35)"
				stroke-width="1"
				stroke-dasharray="6 3"
			/>

			<!-- Port-side mid dashed separator (head area) -->
			<line
				x1="32"
				y1="656"
				x2="206"
				y2="656"
				stroke="rgba(196,146,58,0.28)"
				stroke-width="1"
				stroke-dasharray="4 4"
			/>

			<!-- Separator: middle → aft cabins -->
			<line
				x1="28"
				y1="764"
				x2="392"
				y2="764"
				stroke="#c4923a"
				stroke-width="1.8"
			/>

			<!-- Aft section: centreline + labels -->
			<line
				x1="210"
				y1="764"
				x2="210"
				y2="990"
				stroke="#c4923a"
				stroke-width="1.6"
			/>
			<text
				x="114"
				y="790"
				text-anchor="middle"
				font-size="13"
				font-family="DM Sans"
				font-weight="700"
				fill="rgba(196,146,58,0.6)">C</text
			>
			<text
				x="284"
				y="790"
				text-anchor="middle"
				font-size="13"
				font-family="DM Sans"
				font-weight="700"
				fill="rgba(196,146,58,0.6)">D</text
			>

			<!-- Aft dashed internal separator (D cabin) -->
			<line
				x1="214"
				y1="886"
				x2="388"
				y2="886"
				stroke="rgba(196,146,58,0.28)"
				stroke-width="1"
				stroke-dasharray="4 4"
			/>

			<!-- ── STERN ── -->
			<text
				x="210"
				y="1022"
				text-anchor="middle"
				font-size="11"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.45)"
				letter-spacing="4">RUFA</text
			>
			<text
				x="210"
				y="1054"
				text-anchor="middle"
				font-size="9"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.28)"
				letter-spacing="1">JEANNEAU SUN ODYSSEY 519</text
			>
			<text
				x="210"
				y="1070"
				text-anchor="middle"
				font-size="7"
				font-family="DM Sans"
				fill="rgba(196,146,58,0.16)"
				letter-spacing="1">Sailing Architects · rzut kojowy</text
			>

			<!-- ── INTERACTIVE BERTHS ── -->
			{#each berthSlots as berth (berth.id)}
				{@const state = berthState(berth.id)}
				<g
					class="boat__berth"
					class:boat__berth--clickable={state === 'available' ||
						state === 'hovered'}
					role="button"
					tabindex={state === 'available' ||
					state === 'hovered' ||
					state === 'selected'
						? 0
						: -1}
					aria-label={`Koja ${berth.id} — ${state === 'captain' ? 'kapitan' : state === 'complimentary' ? 'bezpłatna' : state === 'taken' ? 'zajęta' : state === 'selected' ? 'wybrana' : 'dostępna'}`}
					aria-pressed={state === 'selected'}
					aria-disabled={state !== 'available' &&
						state !== 'hovered' &&
						state !== 'selected'}
					onclick={() => handleBerth(berth.id)}
					onkeydown={(e) => handleKey(e, berth.id)}
					onmouseenter={() => (hovered = berth.id)}
					onmouseleave={() => (hovered = null)}
					onfocus={() => (hovered = berth.id)}
					onblur={() => (hovered = null)}
				>
					<rect
						x={berth.x}
						y={berth.y}
						width={berth.w}
						height={berth.h}
						fill={berthFill(berth.id)}
						stroke={berthStroke(berth.id)}
						stroke-width={state === 'selected' ? 3 : 1.6}
						rx="0"
					/>
					{#if state === 'taken'}
						<line
							x1={berth.x + 6}
							y1={berth.y + 6}
							x2={berth.x + berth.w - 6}
							y2={berth.y + berth.h - 6}
							stroke="#3a4a5c"
							stroke-width="1.5"
						/>
					{/if}
					{#if state === 'complimentary'}
						<line
							x1={berth.x + 6}
							y1={berth.y + 6}
							x2={berth.x + berth.w - 6}
							y2={berth.y + berth.h - 6}
							stroke="rgba(196,146,58,0.3)"
							stroke-width="1"
						/>
						<line
							x1={berth.x + berth.w - 6}
							y1={berth.y + 6}
							x2={berth.x + 6}
							y2={berth.y + berth.h - 6}
							stroke="rgba(196,146,58,0.3)"
							stroke-width="1"
						/>
					{/if}
					{#if state === 'selected'}
						<line
							x1={berth.x + berth.w / 2 - 8}
							y1={berth.y + berth.h / 2}
							x2={berth.x + berth.w / 2 + 8}
							y2={berth.y + berth.h / 2}
							stroke="#fff"
							stroke-width="2.5"
						/>
						<line
							x1={berth.x + berth.w / 2}
							y1={berth.y + berth.h / 2 - 8}
							x2={berth.x + berth.w / 2}
							y2={berth.y + berth.h / 2 + 8}
							stroke="#fff"
							stroke-width="2.5"
						/>
					{/if}
					{#if state === 'captain'}
						<!-- Anchor symbol for captain berth -->
						<text
							x={berth.x + berth.w / 2}
							y={berth.y + berth.h / 2 - 6}
							text-anchor="middle"
							dominant-baseline="central"
							font-size="18"
							fill="rgba(196,146,58,0.45)">⚓</text
						>
						<text
							x={berth.x + berth.w / 2}
							y={berth.y + berth.h / 2 + 14}
							text-anchor="middle"
							dominant-baseline="central"
							font-size="9"
							font-family="DM Sans, sans-serif"
							fill="rgba(196,146,58,0.35)"
							letter-spacing="1">SKP</text
						>
					{:else}
						<text
							x={berth.x + berth.w / 2}
							y={berth.y + berth.h / 2}
							text-anchor="middle"
							dominant-baseline="central"
							font-size="14"
							font-family="DM Sans, sans-serif"
							fill={berthLabelColor(berth.id)}
							font-weight="600"
							letter-spacing="0.5">{berth.id}</text
						>
						{#if berth.id === 'E1' || berth.id === 'E2'}
							<text
								x={berth.x + berth.w / 2}
								y={berth.y + berth.h / 2 + 18}
								text-anchor="middle"
								dominant-baseline="central"
								font-size="9"
								font-family="DM Sans, sans-serif"
								fill={berthLabelColor(berth.id)}
								fill-opacity="0.7">{berth.id === 'E1' ? 'dół' : 'góra'}</text
							>
						{/if}
					{/if}
				</g>
			{/each}
		</svg>
	</div>

	<aside class="boat__sidebar">
		<section class="boat__legend">
			<p class="boat__legend-title">Legenda</p>
			<div class="boat__legend-list">
				{#each legend as item (item.label)}
					<div class="boat__legend-item">
						<span
							class="swatch"
							style:background={item.fill}
							style:border-color={item.stroke}
						></span>
						<span class="boat__legend-label">{item.label}</span>
					</div>
				{/each}
			</div>
		</section>

		<section>
			<p class="boat__legend-title">Kajuty</p>
			<ul class="boat__cabins">
				{#each cabins as cabin (cabin.id)}
					<li class="boat__cabin">
						<div class="boat__cabin-text">
							<span class="boat__cabin-label">{cabin.label}</span>
							<span class="boat__cabin-pos">{cabin.position}</span>
						</div>
						<div class="boat__cabin-berths">
							{#each cabin.berths as b (b)}
								{@const state = berthState(b)}
								<button
									type="button"
									class="berth-btn"
									class:berth-btn--selected={state === 'selected'}
									class:berth-btn--taken={state === 'taken'}
									class:berth-btn--captain={state === 'captain'}
									class:berth-btn--complimentary={state === 'complimentary'}
									aria-pressed={state === 'selected'}
									aria-disabled={state !== 'available' &&
										state !== 'hovered' &&
										state !== 'selected'}
									aria-label={`Koja ${b}`}
									onclick={() => handleBerth(b)}
									onmouseenter={() => (hovered = b)}
									onmouseleave={() => (hovered = null)}
								>
									{state === 'captain' ? '⚓' : b}
								</button>
							{/each}
						</div>
					</li>
				{/each}
			</ul>
		</section>

		{#if selectedBerth && selectedCabin}
			<aside class="boat__selected">
				<p class="boat__selected-eyebrow">Wybrana</p>
				<p class="boat__selected-title">Koja {selectedBerth}</p>
				<p class="boat__selected-meta">
					{selectedCabin.label} · {selectedCabin.position}
				</p>
			</aside>
		{/if}
	</aside>
</div>

<style>
	.boat {
		display: flex;
		gap: 32px;
		align-items: flex-start;
		justify-content: center;
		flex-wrap: wrap;
	}

	.boat__svg-wrap {
		position: relative;
	}

	.boat__svg {
		display: block;
	}

	.boat__berth {
		outline: none;
		transition: opacity 150ms ease;
	}

	.boat__berth--clickable {
		cursor: pointer;
	}

	.boat__berth:not(.boat__berth--clickable) {
		cursor: not-allowed;
	}

	.boat__berth:focus-visible rect {
		stroke-width: 4;
	}

	.boat__sidebar {
		min-width: 220px;
		max-width: 280px;
		display: flex;
		flex-direction: column;
		gap: 20px;
	}

	.boat__legend-title {
		font-family: var(--font-sans);
		font-size: 11px;
		letter-spacing: 2px;
		color: rgba(196, 146, 58, 0.7);
		text-transform: uppercase;
		margin: 0 0 12px;
	}

	.boat__legend-list {
		display: flex;
		flex-direction: column;
		gap: 8px;
	}

	.boat__legend-item {
		display: flex;
		align-items: center;
		gap: 10px;
	}

	.swatch {
		width: 20px;
		height: 12px;
		border: 1px solid;
		flex-shrink: 0;
	}

	.boat__legend-label {
		font-family: var(--font-sans);
		font-size: 12px;
		color: rgba(245, 240, 232, 0.6);
	}

	.boat__cabins {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: 6px;
	}

	.boat__cabin {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 8px 12px;
		background: rgba(255, 255, 255, 0.04);
		border-left: 2px solid rgba(196, 146, 58, 0.3);
		gap: 12px;
	}

	.boat__cabin-text {
		min-width: 0;
	}

	.boat__cabin-label {
		font-family: var(--font-serif);
		font-size: 13px;
		color: rgba(245, 240, 232, 0.9);
		font-weight: 600;
		display: block;
	}

	.boat__cabin-pos {
		font-family: var(--font-sans);
		font-size: 10px;
		color: rgba(245, 240, 232, 0.4);
		margin-top: 1px;
		display: block;
	}

	.boat__cabin-berths {
		display: flex;
		gap: 4px;
		flex-shrink: 0;
	}

	.berth-btn {
		width: 28px;
		height: 22px;
		background: transparent;
		border: 1px solid var(--color-brass);
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		font-family: var(--font-sans);
		font-size: 9px;
		font-weight: 700;
		letter-spacing: 0.3px;
		color: var(--color-brass);
		transition:
			background-color 150ms ease,
			color 150ms ease,
			border-color 150ms ease;
		padding: 0;
		border-radius: 0;
	}

	.berth-btn:hover:not(.berth-btn--taken):not(.berth-btn--selected) {
		background: rgba(196, 146, 58, 0.15);
	}

	.berth-btn--selected {
		background: var(--color-brass);
		color: #fff;
	}

	.berth-btn--taken {
		background: rgba(13, 27, 46, 0.5);
		border-color: #3a4a5c;
		color: #3a4a5c;
		cursor: not-allowed;
	}

	.berth-btn--captain {
		background: rgba(8, 18, 36, 0.9);
		border-color: rgba(196, 146, 58, 0.4);
		color: rgba(196, 146, 58, 0.45);
		cursor: not-allowed;
		font-size: 11px;
	}

	.berth-btn--complimentary {
		background: rgba(196, 146, 58, 0.05);
		border-color: rgba(196, 146, 58, 0.3);
		color: rgba(196, 146, 58, 0.35);
		cursor: not-allowed;
	}

	.boat__selected {
		padding: 14px 16px;
		background: rgba(196, 146, 58, 0.12);
		border: 1px solid rgba(196, 146, 58, 0.4);
	}

	.boat__selected-eyebrow {
		font-family: var(--font-sans);
		font-size: 10px;
		letter-spacing: 2px;
		color: var(--color-brass);
		text-transform: uppercase;
		margin: 0 0 4px;
	}

	.boat__selected-title {
		font-family: var(--font-serif);
		font-size: 18px;
		color: var(--color-warm-white);
		margin: 0 0 2px;
	}

	.boat__selected-meta {
		font-family: var(--font-sans);
		font-size: 11px;
		color: rgba(245, 240, 232, 0.5);
		margin: 0;
	}
</style>
